name: fluvius_calculations_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-268.0.dev

dependencies:
  
  flutter:
    sdk: flutter
  file_picker: ^10.3.3
  http: ^1.1.0
  fl_chart: ^1.1.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  google_fonts: ^6.3.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
